[2023-01-26 16:01:12,067] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.send_email_notification scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-26 16:01:12,082] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.send_email_notification scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-26 16:01:12,082] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:01:12,082] {taskinstance.py:1377} INFO - Starting attempt 3 of 3
[2023-01-26 16:01:12,082] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:01:12,102] {taskinstance.py:1397} INFO - Executing <Task(EmailOperator): send_email_notification> on 2023-01-01 00:00:00+00:00
[2023-01-26 16:01:12,107] {standard_task_runner.py:52} INFO - Started process 1333 to run task
[2023-01-26 16:01:12,112] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'send_email_notification', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '531', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmp7eksc1oq', '--error-file', '/tmp/tmpfqg2ymax']
[2023-01-26 16:01:12,113] {standard_task_runner.py:80} INFO - Job 531: Subtask send_email_notification
[2023-01-26 16:01:12,192] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.send_email_notification scheduled__2023-01-01T00:00:00+00:00 [running]> on host fd9891b969b0
[2023-01-26 16:01:12,295] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=send_email_notification
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:00:00+00:00
[2023-01-26 16:01:12,308] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-01-26 16:01:12,308] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2023-01-26 16:01:12,308] {email.py:228} INFO - Email alerting: attempt 1
[2023-01-26 16:01:12,309] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 85, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-01-26 16:01:12,322] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Respuesta_Nasa, task_id=send_email_notification, execution_date=20230101T000000, start_date=20230126T160112, end_date=20230126T160112
[2023-01-26 16:01:12,338] {standard_task_runner.py:97} ERROR - Failed to execute job 531 for task send_email_notification ([Errno 99] Cannot assign requested address; 1333)
[2023-01-26 16:01:12,364] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-26 16:01:12,407] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
